id = "lonely-planet"
name = "Lonely Planet Theme"
version = "0.0.1"
schema_version = 1
authors = ["John Castrillon <https://github.com/jbonez87>"]
description = "Theme for Zed inspired by the vscode-chester-atom theme."
repository = "https://github.com/jbonez87/lonely-planet-theme"
